name: Publish

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  Publish:
    name: Publish with Poetry
    runs-on: ubuntu-latest
    steps:
      - name: Wait for tests to succeed
        uses: lewagon/wait-on-check-action@v1.0.0
        with:
          ref: ${{ github.ref }}
          check-name: "Test"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10.1"
      - uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: "1.1.12"
      - name: Build and publish
        env:
          PYPI_USERNAME: __token__
          PYPI_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          poetry config virtualenvs.in-project true
          poetry install --no-root
          poetry publish --build --username $PYPI_USERNAME --password $PYPI_PASSWORD
      - name: Save dist
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

  Release:
    name: Release
    runs-on: ubuntu-latest
    needs: Publish
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get dist
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - name: Get Tag
        id: tagName
        uses: olegtarasov/get-tag@v2.1.1
      - name: Make Release
        id: release
        env:
          TAG_NAME: ${{ steps.tagName.outputs.tag }}
        run: |
          touch RELEASE.md
          PREVIOUS_TAG="$(git tag -l --sort=-version:refname | head -2 | tail -1)"
          echo "Full changelog: https://github.com/$GITHUB_REPOSITORY/compare/$PREVIOUS_TAG...$TAG_NAME" >> RELEASE.md
          echo "::set-output name=tag::$TAG_NAME"
          echo "::set-output name=release_body::RELEASE.md"
      - name: Release Result
        run: |
          cat RELEASE.md
          printf "\n## Dist Files\n"
          ls -l dist || echo "  no files"
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ steps.release.outputs.tag }}
          name: ${{ steps.release.outputs.tag }}
          body_path: ${{ steps.release.outputs.release_body }}
          files: |
            dist/*