name: Test

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  style-test:
    name: Style Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Style Test
        id: test
        run: |
          python -m pip install flake8
          python -m flake8 --max-line-length=120 faapi

  types-test:
    name: Types Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Types test
        id: test
        run: |
          python -m pip install mypy types-beautifulsoup4
          python -m mypy --install-types --non-interactive faapi
