name: Test

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  style-test:
    name: Style test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Style test
        id: test
        run: |
          python -m pip install flake8
          python -m flake8 --max-line-length=120 faapi
    outputs:
      outcome: ${{ steps.test.outcome }}

  types-test:
    name: Types Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Types test
        id: test
        run: |
          python -m pip install mypy types-beautifulsoup4
          python -m mypy --install-types --non-interactive faapi
    outputs:
      outcome: ${{ steps.test.outcome }}

  test-end:
    name: Test End
    runs-on: ubuntu-latest
    needs: [ style-test, types-test ]
    if: always()
    steps:
      - name: Tests Results
        run: |
          echo "Style test: ${{ needs.style-test.outputs.outcome }}"
          echo "Types test: ${{ needs.types-test.outputs.outcome }}"
      - name: Fail
        if: ${{ needs.style-test.outputs.outcome != 'success' || needs.types-test.outputs.outcome != 'success' }}
        run: exit 1
