name: Test

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  flake8:
    name: Flake8
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.10.2", "3.9.12"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Style Test
        id: test
        run: |
          python -m pip install flake8
          python -m flake8 --max-line-length=120 faapi

  mypy:
    name: mypy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.10.2", "3.9.12"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Types test
        id: test
        run: |
          python -m pip install mypy types-beautifulsoup4
          python -m mypy --install-types --non-interactive faapi
