name: Test

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  PYTHON_VERSION: 3.10.2

jobs:
  flake8:
    name: Flake8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Style Test
        id: test
        run: |
          python -m pip install flake8
          python -m flake8 --max-line-length=120 faapi

  mypy:
    name: mypy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Types test
        id: test
        run: |
          python -m pip install mypy types-beautifulsoup4
          python -m mypy --install-types --non-interactive faapi
